# Generated by Django 5.0.6 on 2024-08-08 06:49

import sitesettings.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    sitesettings.models.UnderscoreCharField(
                        max_length=250, unique=True
                    ),
                ),
                ("value", models.CharField(max_length=250)),
            ],
        ),
    ]
