# Generated by Django 5.0.6 on 2024-08-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l3meetings", "0002_meeting_next_moderator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="next_moderator",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_date",
            field=models.DateTimeField(),
        ),
    ]
