# Generated by Django 5.0.6 on 2024-08-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l3meetings", "0005_meetingnotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionitem",
            name="actual_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionitem",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="actionitem",
            name="target_end_date",
            field=models.DateTimeField(),
        ),
    ]
