# Generated by Django 5.0.6 on 2024-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l3meetings", "0008_alter_meeting_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="title",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
