# Generated by Django 5.1.1 on 2024-09-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="local_file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="song",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
