# Generated by Django 5.1.1 on 2024-09-09 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0003_song_local_file_path_alter_song_artist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="local_file_path",
        ),
    ]
