# Generated by Django 5.1.1 on 2024-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0004_remove_song_local_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
    ]
