# Generated by Django 5.1.1 on 2024-09-10 12:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_song_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="music.musiccategory"
            ),
        ),
    ]
