# Generated by Django 5.1.1 on 2024-09-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0006_song_created_at_alter_song_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="music.musiccategory",
            ),
        ),
    ]
