# Generated by Django 5.1.1 on 2024-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_alter_song_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="url",
        ),
    ]
