# Generated by Django 5.0.6 on 2024-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("l3users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="employee_id",
            field=models.CharField(max_length=10),
        ),
    ]
