# Generated by Django 5.0.6 on 2024-07-22 07:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("l3meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingInvites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invite_details", ckeditor.fields.RichTextField()),
                ("invitees", models.TextField(default="")),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="l3meetings.meeting",
                    ),
                ),
            ],
        ),
    ]
